# -*- coding: utf-8 -*-
"""Dictionaries

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PZgp-9JUOPEUYXY5hbm0xy7iHK8NZfl_
"""

#Q1
no_of_products= eval(input("Enter Number of Products: "))
my_dict ={}
for i in range(no_of_products):
    nameofproduct = input("Enter Product Name: ")
    priceofproduct = int(input("Enter Product Price: "))
    my_dict[nameofproduct] = priceofproduct


while True:
    nameofproduct = input("Enter Product name to get Price or 1 to end: ")
    if nameofproduct in my_dict:
        print("The price for your product is ", my_dict[nameofproduct])
    if nameofproduct=="1":
      break
    else:
        print("This product is not found in dictionary")


print(my_dict)

#Q2
loop = int(input("Enter how many items you want to add to your dictionary:"))
dic = {}
for i in range(loop):
  product = input("enter the product name:").lower() 
  price = int(input("enter the price of the product:"))
  dic[product] = price
dollar = int(input("enter the amount:"))
for key ,values in dic.items():
  if int(values)<dollar :
    print(key)

#Q3
my_dic = {'january':31, 'february':28, 'march':31, 'april':30,
'may':31, 'june':30, 'july':31, 'august':31,
'september':30, 'october':31, 'november':30, 'december':31}

# part a
month = input("Enter the name of month: ").lower()
print("The number of days in ",month,' are ',my_dic[month])

#part b
print(sorted(my_dic))

#part c
for key ,values in my_dic.items():
  if int(values)==31:
    print(key)

#Q8
import random

all_card ={"One":1,"Two":2,"Three":3,"Four":4,"Five":5,"Six":6,"Seven":7,"Eight":8,"Nine":9,"Ten":10}
cards = 3
player1Card =[]
player2Card =[]
for card in range(cards):
    card1 =random.choice(list(all_card.values()))
    card2= random.choice(list(all_card.values()))
    player1Card.append(card1)
    player2Card.append(card2)
print(player1Card,player2Card)

if sum(player1Card) > sum(player2Card):
    print("Player 1 wins with ",sum(player1Card)," Against Player 2 with",sum(player2Card))
elif sum(player2Card) > sum(player1Card):
    print("Player 2 wins with ",sum(player2Card)," Against Player 1 with",sum(player1Card))

